### ISSUE TITLE
[2024-06-27]: TMBad

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/seaside-chats#5]
### Who will lead the topic?

@Andrea-Havron-NOAA

### Topic description

What is TMBad and how is it different than using CppAD?

### Topic background

NOAA-FIMS/FIMS#210 discusses some initial pros and cons of moving to TMBad from CppAD within TMB. The move will require changes in the C++ portion of the FIMS code. See a [comment in FIMS#210](https://github.com/NOAA-FIMS/FIMS/issues/210#issuecomment-2195217891) for a list of changes required.

### Topic outline

* What is TMBad
  * Initiated with TMB 1.8.0 (2022-03-07)
  * see `?TMB::compile`
* What is CppAD
* What are the benefits of staying with CppAD
  * Widely used by more than just TMB
* What are the benefits of moving to TMBad
  * faster computations with certain hessian structures that do not meet the usual sparsity requirement by clipping the tape
  * More advancements are happening in TMBad
  * more readable than CppAD.
  * `intern=TRUE` allows for the entire Laplace approximation (including sparse matrix calculations) to be done within the AD machinery on the C++ side and provides an autodiff hessian (obj$he) wrt the fixed effects but can only be done using TMBad; consider also compiling with `supernodal=TRUE` to get performance comparable to R’s matrix calculations.
  * Bias correction is faster due to some rank-reduced thing
  * At some point, Kasper will deprecate the use of CppAD and then we will need to switch
  * Reduced amount of code in RCPP interface
* Drawbacks of CppAD
  * TMB is not kept up to date with the latest version of CppAD, TMB uses a static version of CppAD from 2015
* Drawbacks of TMBad
  * random effects are no longer visible in the model environment which may break assumptions on the layout of internal vectors (`par`, `last.par`) if `intern = TRUE`
  * ~~Requires users install TMB 1.8.0 and higher but we already require that~~
  * Model debugging becomes harder when calculations are moved to C++

### Topic resources

* [CppAD](https://github.com/coin-or/CppAD)
* [Compiling instructions](https://rdrr.io/cran/TMB/man/compile.html) for TMBad

```[tasklist]
### Tasks
```

**Comment by kellijohnson-NOAA** [comment]
@Andrea-Havron-NOAA are you willing to lead this discussion in a seaside chat? If yes, please modify the date in the title to a Thursday that works for you and assign yourself to this issue.

**Comment by Andrea-Havron-NOAA** [comment]
I can discuss TMBad this week - otherwise I will need to wait until August.

**Comment by Andrea-Havron-NOAA** [comment]
Drawbacks of TMBad:
* random effects are no longer visible in the model environment which may break assumptions on the layout of internal vectors (par, last.par)

Could the person who added this drawback provide an example? I have a working random effects model compiled with TMBad and I can still see the random effects in the model environment, that is, `obj$env$last.par` and `obj$env$last.par.best`

**Comment by kellijohnson-NOAA** [comment]
@Andrea-Havron-NOAA Here is the [link to the TMB documentation](https://cran.r-project.org/web/packages/TMB/TMB.pdf) where I found the following:
![image](https://github.com/NOAA-FIMS/seaside-chats/assets/4108564/3cb936a4-909a-4fc1-adf3-db93143be3f5)

**Comment by Andrea-Havron-NOAA** [comment]
Thanks @kellijohnson-NOAA! It is worth noting this is only a drawback when specifying intern=TRUE, otherwise, there are no differences in output between CppAD and TMBad

**Comment by kellijohnson-NOAA** [comment]
The move to TMBad will not occur until after M2 is complete.
