### ISSUE TITLE
[2024-07-11]: How to model discards

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/seaside-chats#6]
### Who will lead the topic?

kellijohnson-NOAA

### Topic description

How to model discards in FIMS.

### Topic background

Yesterday in the Implementation Team Meeting we talked about how discards are currently modelled and what discard data looks like but we did not decide how to move forward with discards in FIMS. This topic needs to be discussed further to create a clear path for how FIMS will model discards in M3.

### Topic outline

* Proposals on how to model it by
  * @iantaylor-NOAA 
  * @nathanvaughan-NOAA 
  * @KyleShertzer-NOAA 
  * @cmlegault 
  * @JonBrodziak 
  * @msupernaw 
  * @kellijohnson-NOAA 
* Pros and cons of each method

### Topic resources

* [Implementation Team Notes](https://docs.google.com/document/d/10nSfbPaBF2p7wL2cr5lW7PGZxlZI4tbPiwQRC8JKaXk/edit#heading=h.q0cntnst0xrw)
* [Kyle's paper](https://www.mdpi.com/2410-3888/7/1/7)
* National Standard 9

**Comment by kellijohnson-NOAA** [comment]
In no current order of prioritization but in order of availability where d does not exist in FIMS
a. ignore discards (pretend that they do not exist)
b. pool dead discards in with landings (if selectivity of discards is very similar to landings)
  - Is this easier in the NE where you have estimates of the "discarded catch" compared to SE where there are functional forms? Focused on empirical weights-at-age data in NE so there are few length-based assessments. Often estimate selectivity-at-age rather than using a functional form.
c. model dead discards as their own fleet
  - Input a time series of discarded tons
  - Input a time series of F because it is a bycatch Fleet (NEEDS DISCUSSION) if we can fix the F parameters in a time series then we can already do this option but it is not intuitive
  - Would need to consider how to handle discards in the benchmarks because we would not want to include them in the forecast as being maximized so we do not want this in MSY
  - We need to structure the fleet class potentially to have sub class to have discards. 
  - Feed the model a time series of dead discards so you need an estimate of the discard mortality outside of the model to get the dead discards.
d. retention function approach (e.g., SS3)
  - most often these are length-based processes
  - would we want age-based retention?
  - only option that would also need discard mortality rate as a function of size or age in the model
  - FIMSFrame does not have a column to designate partition versus retained for composition or catch data

**Comment by kellijohnson-NOAA** [comment]
VOTES
a 👎 (7)

**Comment by kellijohnson-NOAA** [comment]
Should we be "predicting unobserved quantities" on discards for when there are no observers or should be put in uninformative catches? Unreported catches or discards can be handled with priors (annual), e.g., Main Hawaiian Islands deep 7 bottomfish assessment since 2011. Time series of tuna models often do not have good time series catch. We are trying to estimate unobserved time series, often discards and landed catch. What quantities do we know best? In some cases fishing effort/mortality is well measured but the fish that were thrown overboard are not well measured. In other cases the size of the discarded fish versus the retained fish are well known and retention curves are well informed. 

We should not ignore them because then we assume that they are ZERO, which is FALSE ☹️ . There is a bias if we do not include them. We end up underestimating biomass if they are ignored. 

DATA will dictate how to best go forward given the lack of data.

**Comment by kellijohnson-NOAA** [comment]
Want to have a capacity for ensemble modeling.

**Comment by kellijohnson-NOAA** [comment]
Fleet module can handle discards right now but would need something different in the future for projections and reference points. Maybe an additional flag if you want to include the fleet in projections and reference points. 
+1 to a component of the fleet module rather than a separate thing

Reuse selectivity functions to kill the fish for the retention function.

Is it possible to Wrap up discards in a random effect? It would be great to have the parameters of the retention function into random effects. Random variation in what was discarded by year. WHAM has random effects in selectivity but it jams everything together and deals with dead fish. But you could set up a discard fleet.

**Comment by kellijohnson-NOAA** [comment]
Projections - Model rolls forward those fleets and how much effort they are putting in but MSY includes discards using the proxy. The landed fraction meets the proportion that they want. Discards flow with that but it is unrealistic to think that discards will be slashed when catches are slashed. 

As stocks rebuild recreational and commercial fisheries have different capacities to rebuild.

**Comment by kellijohnson-NOAA** [comment]
Ian +1
Kyle +1
Nathan +1
Chris +1
Jon +1
Matthew +1
Kelli - will organize leaders but not participate in every meeting

**Comment by iantaylor-NOAA** [comment]
I see that the [requirements document](https://docs.google.com/spreadsheets/d/1impCdPPob8IPdoiFDpJpe7-Nbdjbz_Uq05_4BWooY4g/edit?gid=1133225771#gid=1133225771) has included these three requirements related to discards since 2021 (some of the details were added more recently):
  | Topic | d | Topic_ | Feature | Impact | Effort | Compatibility | Score | Detailed description | Note | Status | Milestone | M2 Theme | Jane's notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
138 | Parameterization | Discard | NA | retention selectivity | 1 | 1 | 1 | 4 | NA | NA |   | 2 |   | M2 High Priority |   |   |   |   |   |   |   |   |   |   |   |  
139 | Parameterization | Discard | NA | discards as separate fleet | 1 | 1 | 1 | 4 | NA | NA |   | 2 |   | M2 High Priority |   |   |   |   |   |   |   |   |   |   |   |  
140 | Parameterization | Discard | NA | mortality (not always 100%, potentially time-varying) | 1 | 1 | 1 | 4 | NA | NA |   | 2 |   | M2 High Priority |   |   |   |   |   |   |   |   |   |   |   |

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, @KyleShertzer-NOAA, @nathanvaughan-NOAA, @JonBrodziak, and @msupernaw:

@cmlegault and I have put together a draft design document for how to include discards in FIMS in M3. Feel free to take a look and make any suggestions as you see fit, https://docs.google.com/document/d/1QBGyKVN5-YXKfJazbdALgbdE2jIYzzZqBtKEGLegt-U/edit?pli=1.

**Comment by kellijohnson-NOAA** [comment]
Closing because these notes are now in the Implementation Team Notes.
