### ISSUE TITLE
[2024-07-25]: Determine authorship policies

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/seaside-chats#8]
### Who will lead the topic?
@iantaylor-NOAA

### Topic description
How will authorship be determined in FIMS and where will "authors" (however they are defined) be listed?

### Topic background
I noticed that @ChristineStawitz-NOAA is listed as "maintainer" on the FIMS landing page https://noaa-fims.github.io/FIMS/ (with all members of the team listed as "author"). The maintainer designation comes from the presence of ["cre" on this line](https://github.com/NOAA-FIMS/FIMS/blob/8aacee04b206787f0f09054cf4202da42a1e674f/DESCRIPTION#L5).

### Topic outline
* Where do we often think about authorship with respect to FIMS
  * presentation authorship order and list,
  * R package authorship (i.e., creator, maintainer, contributor),
  * advocator for continued support in terms of national funding, etc.
  * idea contributor
  * code contributor
* What do individuals who are acknowledged as authors get in return?
  * Acknowledgement of contributions
  * A potential desire to continue their support of the project
  * Recognition on for their Performance Plan
  * Creating points of contact
  * <fill in more?>
* What types of authorship should be documented/standardized and published for people to clearly see?
  * Where should the authorship list(s) live?
  * What is the goal of including people in the [DESCRIPTION file](https://github.com/NOAA-FIMS/FIMS/blob/39d07434dd5b719a56f70a383cb381408535c0fd/DESCRIPTION#L4)?
  * How much of a contribution must one give to the code to be listed on the DESCRIPTION file? Should all current and past members of the FIMS implementation team be listed as authors?
  * Will individuals that are no longer contributing still be listed?
  * What happens when someone changes their GitHub user name, is that something we even need to worry about?
  * Should the project lead always be listed as maintainer?
  * When folks outside the FIMS implementation team create pull requests that get merged in the future, do they get added to the author list?
  * How is authorship decided upon for presentations?

### Topic resources
* [Info on the Authors@R field](https://r-pkgs.org/description.html#sec-description-authors-at-r) used in the DESCRIPTION file of R packages
* [Example of R package format in use at stan](https://mc-stan.org/rstan/authors.html)
* Examples authorship lists that don't follow R package format and have more nuance
  * https://mc-stan.org/about/team/
  * https://www.r-project.org/contributors.html

**Comment by iantaylor-NOAA** [comment]
Yes, I can lead this. I'm available for most of the upcoming seaside chats.

**Comment by kellijohnson-NOAA** [comment]
Closing because I moved it to an issue in collaborative workflow and notes are in the Implementation Team Meeting running document.
