### ISSUE TITLE
[2024-08-01]: FIMS manuscript feedback on Figures and Tables

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/seaside-chats#9]
### Who will lead the topic?

ChristineStawitz-NOAA

### Topic description

Get feedback on the Figures and Tables in the FIMS manuscript.

### Topic background

@ChristineStawitz-NOAA please feel free to edit this comment to describe the necessary background.

### Topic outline

* Review Figures
* Review Tables
* Create next steps

### Topic resources

* [FIMS paper message (figs and tables)](https://docs.google.com/document/d/1nrtZRz4gDbxz6YTtu3CX3n1_KY4RbaAOxQSOVJ-rJuc/edit?usp=sharing) (only NOAA employees can access the link)
* [full FIMS manuscript](https://docs.google.com/document/d/1nvhB8glk3PJ-O_wQtIbLAWo5sc5yWtjEUhZ8BUHQyh8/edit) (only NOAA employees can access the link)

**Comment by ChristineStawitz-NOAA** [comment]
I'm aiming to update the figures and captions by the end of next week to share for team feedback

**Comment by kellijohnson-NOAA** [comment]
Figures and tables have been shared with the larger group, see @ChristineStawitz-NOAA's email. Code to create those elements was also shared in a reply to that same email.
